version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password123}
      - MYSQL_USER=${MYSQL_USER:-cernera}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password123}
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.2.3-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - web-root-wordpress:/usr/share/nginx/wordpress
    networks:
      - app-network

  nginx:
    depends_on:
      - db
      - wordpress
    build:
      context: ./nginx/public
      dockerfile: Dockerfile
    container_name: web_server
    restart: unless-stopped
    volumes:
      - web-root:/usr/share/nginx/cernera_me
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
      - ./dhparam/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - wordpress
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-etc:/var/www/certbot
      - web-root:/usr/share/nginx/cernera_me
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/usr/share/nginx/cernera_me --email cernerae@gmail.com --agree-tos --no-eff-email --force-renewal -d cernera.me
volumes:
  certbot-etc:
  certbot-var:
  dbdata:
  web-root:
  web-root-wordpress:

networks:
  app-network:
    driver: bridge  
