version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password123}
      - MYSQL_USER=${MYSQL_USER:-cernera}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password123}
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.2.3-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - db
      - wordpress
    build:
      context: ./nginx/public
      dockerfile: Dockerfile
    container_name: web_server
    volumes:
      - ./nginx/public/nginx.conf:/etc/nginx/nginx.conf
      - ./cert/data/certbot/conf:/etc/letsencrypt
      - ./cert/data/certbot/www:/var/www/certbot
      - wordpress:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./cert/data/certbot/conf:/etc/letsencrypt
      - ./cert/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge  
